### ISSUE TITLE
how to enable a very large number of PRBs?

### ISSUE THREAD

**Issue by mhmd97z** [jjalcaraz-upct/network-slicing#2]
Hi,
I'm running a few experiments using your code. I increased the number of PRBs above 200, but it seems that it is not supported.
Could you give some hints on where the bottleneck is and how I can increase the capacity of PRBs?
Thanks

**Comment by jjalcaraz-upct** [comment]
Hi,

Thank you for using my code. The reason why the code doesn’t work for a number of PRBs above 200 is because the files containing the SINR traces were obtained for only 100 PRBs, i.e. they contain 100 rows of SINR samples. Therefore, when the number of PRBs exceeds 100, the code stacks duplicate rows on top of the original ones, so that there is maximum frequency distance between a duplicate and the original. The code can get up to 200 PRBs with all rows duplicated. All this is done in the SINRSelectiveFading class, defined in channel_models.py. It is not hard to modify it to allow for a larger PRB extension.

BR,

Juanjo

From: Mohammad Zangooei ***@***.***>
Reply-To: jjalcaraz-upct/network-slicing ***@***.***>
Date: Friday, October 14, 2022 at 3:09 AM
To: jjalcaraz-upct/network-slicing ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jjalcaraz-upct/network-slicing] how to enable a very large number of PRBs? (Issue #2)


Hi,
I'm running a few experiments using your code. I increased the number of PRBs above 200, but it seems that it is not supported.
Could you give some hints on where the bottleneck is and how I can increase the capacity of PRBs?
Thanks
